export const actions = {
    TITLE_CHANGE: 'TITLE_CHANGE',
    DESCRIPTION_CHANGE: 'DESCRIPTION_CHANGE',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    UPDATE_LISTS: 'UPDATE_LISTS',
    DELETE_LIST: 'DELETE_LIST'
}
  