export const actions = {
    TITLE_CHANGE: 'TITLE_CHANGE',
    DESCRIPTION_CHANGE: 'DESCRIPTION_CHANGE',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    UPDATE_LISTS: 'UPDATE_LISTS',
    DELETE_LIST: 'DELETE_LIST',
    DELETE_LIST_RESULT: 'DELETE_LIST_RESULT',
    EDIT_LIST: "EDIT_LIST",
    UPDATE_LIST_RESULT: 'UPDATE_LIST_RESULT'
}
  